### ISSUE TITLE
MutableMapping ImportError python 3.10

### ISSUE THREAD

**Issue by Petchesi-Iulian** [klahnakoski/mo-sql-parsing#171]
Hello, I am encountering the following error and I am wondering what I am doing wrong.

Here are my versions:
```
mo-sql-parsing==9.367.23090
mo-parsing==8.366.23085
mo-future==7.340.23006
mo-dots==9.365.23080
```

and in my code I am calling

`from mo_sql_parsing import format as sql_format`

Which results in the following error:
```
  File "/lib/python3.10/site-packages/mo_sql_parsing/__init__.py", line 15, in <module>
    from mo_parsing import debug
  File "/lib/python3.10/site-packages/mo_parsing/__init__.py", line 97, in <module>
    from mo_parsing.core import ParserElement, _PendingSkip
  File "/lib/python3.10/site-packages/mo_parsing/core.py", line 16, in <module>
    from mo_parsing.results import ParseResults
  File "/lib/python3.10/site-packages/mo_parsing/results.py", line 3, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
The packages are installed with Pip.

**Comment by klahnakoski** [comment]
thank you for this.  Obviously my install tests have failed!  Looking...

**Comment by klahnakoski** [comment]
@Petchesi-Iulian 

the last time mo-parsing used `from collections import MutableMapping` was Dec 2020 (version 4.x)

https://github.com/klahnakoski/mo-parsing/commit/d5c2b7b16d73d3df1e543a7a87d1efb1c5e06899

The current version is 8.x.  Please try 

    pip install --upgrade mo-sql-parsing

Maybe you are locked to version 4?  Please see if any of [these breaking changes apply to you](https://github.com/klahnakoski/mo-sql-parsing#version-8200).  If so, then I would be interested in trying to branch version 4.x to work with 3.10.


 Thank you for bringing this to my attention.

**Comment by Petchesi-Iulian** [comment]
@klahnakoski  thank you for your reply!

I tried doing the pip upgrade but nothing seems changed:
```
pip3 install --upgrade mo-sql-parsing
Requirement already satisfied: mo-sql-parsing in ./lib/python3.10/site-packages (9.367.23090)
Requirement already satisfied: mo-dots==9.365.23080 in ./lib/python3.10/site-packages (from mo-sql-parsing) (9.365.23080)
Requirement already satisfied: mo-parsing==8.366.23085 in ./lib/python3.10/site-packages (from mo-sql-parsing) (8.366.23085)
Requirement already satisfied: mo-future==7.340.23006 in ./lib/python3.10/site-packages (from mo-sql-parsing) (7.340.23006)
Requirement already satisfied: mo-imports==7.365.23080 in ./lib/python3.10/site-packages (from mo-sql-parsing) (7.365.23080)
```
I get the feeling that for some reason I am locked to this version, will look into those breaking changes.

**Comment by Petchesi-Iulian** [comment]
Upon closer examination of my environment, I found a rogue pin of the https://github.com/mozilla/moz-sql-parser package.

From what I can tell it was getting its dependencies first and that's the reason I was locked to an older mo-parsing version. After getting rid of the pin, the code now correctly gets the latest Pypi version.

Sorry for being a trouble with this and thanks for your help!
